services:
    transcendence:
        container_name: transcendence
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - webnet
        depends_on:
            - postgres
        restart: on-failure:5

    postgres:
        container_name: postgres
        image: postgres:latest
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./data/postgres/:/var/lib/postgresql/data
        networks:
            - webnet

    # pgadmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     container_name: pgadmin4
    #     ports:
    #         - '5050:80'
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: ts@ts.com
    #         PGADMIN_DEFAULT_PASSWORD: 1234
    #     volumes:
    #         - ./data/pgadmin/:/var/lib/pgadmin
networks:
    webnet:
